### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jjplaying** [jjplaying/Worlds#2]
Next things todo:

- [x] Add option to load all worlds at once with world load command
- [x] Add create world command
- [x] Options to create flat world or nether
- [x] Finish delete world command
